/**
 * normalizeConfirmedJournals.ts — 既存confirmed_journalsの一括正規化（CLI）
 *
 * 【設計原則: DL-050】
 * このスクリプトは NormalizeService を呼ぶだけ。
 * ビジネスロジックもファイル直接操作も一切しない。
 *
 * 使い方:
 *   npx tsx src/scripts/normalizeConfirmedJournals.ts [--dry-run]
 *
 * オプション:
 *   --dry-run  実際に書き込まず、変換結果のみ表示
 */

import { config } from 'dotenv'
import { join } from 'path'

// .env.local からGEMINI_API_KEYを読み込む
config({ path: join(process.cwd(), '.env.local') })

// ApplicationService（唯一の正規化ロジック）
import { normalizeConfirmedJournals } from '../api/services/normalizeConfirmedJournalsService'

const isDryRun = process.argv.includes('--dry-run')

async function main() {
  console.log('=== confirmed_journals 一括正規化 ===')
  console.log(`モード: ${isDryRun ? 'ドライラン（書き込みなし）' : '実行'}`)
  console.log('')

  // NormalizeService を呼ぶだけ（DL-050）
  const result = await normalizeConfirmedJournals({ dryRun: isDryRun })

  // 結果表示
  console.log('\n=== 変換結果 ===')
  console.log(`対象仕訳: ${result.journalCount}件`)
  console.log(`科目:`)
  console.log(`  マスタヒット変換: ${result.accountConverted}件`)
  console.log(`  自動発番: ${result.accountAutoGenerated}件`)
  console.log(`  正規化済み（スキップ）: ${result.accountAlreadyNormalized}件`)

  console.log(`\n税区分:`)
  console.log(`  変換成功: ${result.taxConverted}件`)
  console.log(`  正規化済み（スキップ）: ${result.taxAlreadyNormalized}件`)
  console.log(`  null（スキップ）: ${result.taxNull}件`)
  console.log(`  変換失敗（MISS）: ${result.taxMiss}件`)
  if (result.missedTaxNames.length > 0) {
    console.log(`  MISS税区分名: ${result.missedTaxNames.join(', ')}`)
  }

  if (result.autoGeneratedAccounts.length > 0) {
    console.log('\n=== 自動発番科目 ===')
    for (const a of result.autoGeneratedAccounts) {
      console.log(`  ${a.clientId}: ${a.name}→${a.accountId}`)
    }
  }

  if (result.dryRun) {
    console.log('\n[ドライラン] 書き込みは行いませんでした')
  } else {
    console.log('\n✅ 正規化完了（インメモリ+ファイル一貫更新済み）')
  }
}

main().catch(err => {
  console.error('エラー:', err)
  process.exit(1)
})
