/**
 * normalizeConfirmedJournalsService.ts — 確定済み仕訳の一括正規化サービス
 *
 * 【設計原則: DL-050】
 * データ変更は Application Service 経由のみ。
 * このサービスが唯一の正規化ロジック。APIもCLIも同じサービスを呼ぶ。
 *
 * 【責務】
 * - confirmed_journals の account/tax_category_id を MF名 → accountId/taxCategoryId に正規化
 * - マスタ外科目は generateMasterId() で自動発番し mf-accounts に自動登録
 * - 名前違い（消耗品→消耗品費等）は ALIAS_MAP で吸収
 *
 * 【データアクセス】
 * - 読み取り: confirmedJournalsApi.getAll()
 * - 書き込み: confirmedJournalsApi.replaceAll()
 * - 科目マスタ: accountMasterApi (getAllAccounts, getClientAccounts, saveMfAccounts)
 * - 税区分マスタ: accountMasterApi (getAllTaxCategories)
 *
 * ファイル直接操作（readFileSync/writeFileSync）は禁止。
 *
 * 準拠: DL-050, DL-042
 */

import { getAll, replaceAll } from './confirmedJournalsApi'
import {
  getAllAccounts,
  getClientAccounts,
  hasClientAccounts,
  saveMfAccounts,
  getAllTaxCategories,
} from './accountMasterApi'
import { getById as getClientById } from './clientsApi'
import { isIndividualType } from '../../constants/clientOptions'
import { generateMasterId } from './generateMasterId'
import type { ConfirmedJournal } from '../../types/confirmed_journal.type'
import type { Account } from '../../types/account.type'

// ────────────────────────────────────────────
// 定数
// ────────────────────────────────────────────

/** 名前違いの吸収マップ（MFマスタと異なる名称でCSVに入った科目） */
const ALIAS_MAP: Record<string, string> = {
  '消耗品': '消耗品費',
  '給料手当': '給料賃金',
}

// ────────────────────────────────────────────
// 型定義
// ────────────────────────────────────────────

export interface NormalizeResult {
  /** 処理対象の仕訳件数 */
  journalCount: number
  /** 科目: マスタヒット変換数 */
  accountConverted: number
  /** 科目: 自動発番数 */
  accountAutoGenerated: number
  /** 科目: 正規化済みスキップ数 */
  accountAlreadyNormalized: number
  /** 税区分: 変換成功数 */
  taxConverted: number
  /** 税区分: 正規化済みスキップ数 */
  taxAlreadyNormalized: number
  /** 税区分: null（スキップ）数 */
  taxNull: number
  /** 税区分: 変換失敗（MISS）数 */
  taxMiss: number
  /** MISS税区分名一覧 */
  missedTaxNames: string[]
  /** 自動発番した科目（顧問先別） */
  autoGeneratedAccounts: Array<{ clientId: string; name: string; accountId: string }>
  /** ドライランかどうか */
  dryRun: boolean
}

// ────────────────────────────────────────────
// 内部ヘルパー
// ────────────────────────────────────────────

/** accountId形式（大文字英数+アンダースコア）かどうか */
function isAlreadyNormalized(value: string): boolean {
  return /^[A-Z][A-Z0-9_]+$/.test(value)
}

/** 顧問先のサフィックスを判定（CORP or IND） */
function getSuffix(clientId: string): string {
  try {
    const client = getClientById(clientId)
    if (client && isIndividualType(client.type)) return 'IND'
  } catch { /* clientServiceが動かない場合はCORP */ }
  return 'CORP'
}

/**
 * 全社マスタ + 顧問先別MFデータから名前→accountIdの逆マップを構築
 * accountMasterApi 経由で取得（ファイル直接読みしない）
 */
function buildAccountNameToIdMap(): { map: Map<string, string>; existingIds: Set<string> } {
  const map = new Map<string, string>()
  const existingIds = new Set<string>()

  // 全社マスタ — suffix付きキーも登録して CORP/IND を選び分け可能にする
  const allAccounts = getAllAccounts()
  for (const a of allAccounts) {
    map.set(a.name, a.accountId)
    existingIds.add(a.accountId)
    const suffixMatch = a.accountId.match(/_(CORP|IND|FUDOUSAN_IND)$/)
    if (suffixMatch) {
      map.set(`${a.name}__${suffixMatch[1]}`, a.accountId)
    }
  }

  // 顧問先別MFデータ（accountMasterApiのインメモリストア経由）
  // getAll()で全顧問先のconfirmedを取得し、client_idを収集
  const journals = getAll()
  const clientIds = new Set(journals.map(j => j.client_id))

  for (const clientId of clientIds) {
    if (hasClientAccounts(clientId)) {
      try {
        const clientData = getClientAccounts(clientId)
        const accounts = clientData.accounts
        for (const a of accounts) {
          map.set(a.name, a.accountId)
          existingIds.add(a.accountId)
        }
      } catch { /* 未保存の場合はスキップ */ }
    }
  }

  return { map, existingIds }
}

/**
 * 税区分マスタから名前→taxCategoryIdの逆マップを構築
 * accountMasterApi 経由で取得
 */
function buildTaxNameToIdMap(): Map<string, string> {
  const map = new Map<string, string>()

  const allTaxes = getAllTaxCategories()
  for (const t of allTaxes) {
    map.set(t.name, t.taxCategoryId)
  }

  return map
}

// ────────────────────────────────────────────
// メインサービス
// ────────────────────────────────────────────

/**
 * 確定済み仕訳の一括正規化を実行する
 *
 * - dryRun=true の場合、データ変更は行わず結果のみ返す
 * - dryRun=false の場合、replaceAll() でインメモリ+ファイルを一貫更新
 *
 * @param options.dryRun - ドライランモード（デフォルト: false）
 */
export async function normalizeConfirmedJournals(
  options: { dryRun?: boolean } = {},
): Promise<NormalizeResult> {
  const dryRun = options.dryRun ?? false

  // 1. マップ構築（accountMasterApi経由）
  const { map: accountMap, existingIds } = buildAccountNameToIdMap()
  const taxMap = buildTaxNameToIdMap()

  // 2. データ取得（confirmedJournalsApi経由 = Repository層）
  const journals = getAll()

  // 3. 変換統計
  let accountConverted = 0
  let accountAlreadyNormalized = 0
  let accountAutoGenerated = 0
  let taxConverted = 0
  let taxAlreadyNormalized = 0
  let taxMiss = 0
  let taxNull = 0
  const missedTaxes = new Set<string>()
  const autoGeneratedAccounts: NormalizeResult['autoGeneratedAccounts'] = []

  // 自動発番した科目の蓄積（顧問先別）
  const newAccountsByClient = new Map<string, Account[]>()
  // 発番済みキャッシュ（同じ科目名の2件目以降で再利用）
  const autoGeneratedCache = new Map<string, string>()

  // 4. 変換処理
  for (const journal of journals) {
    const entries = [...journal.debit_entries, ...journal.credit_entries]
    for (const entry of entries) {
      // ── 科目変換 ──
      if (isAlreadyNormalized(entry.account)) {
        accountAlreadyNormalized++
      } else {
        // 名前違い吸収（消耗品→消耗品費 等）
        const aliasName = ALIAS_MAP[entry.account]
        const lookupName = aliasName ?? entry.account

        // suffix付きキーで優先検索（CORP/IND選び分け）
        const suffix = getSuffix(journal.client_id)
        const id = accountMap.get(`${lookupName}__${suffix}`) ?? accountMap.get(lookupName)

        if (id) {
          if (!dryRun) entry.account = id
          accountConverted++
        } else {
          // マスタ外科目 → generateMasterIdで自動発番
          const cacheKey = `${journal.client_id}:${entry.account}`
          let generatedId = autoGeneratedCache.get(cacheKey)

          if (!generatedId) {
            generatedId = await generateMasterId(entry.account, suffix, existingIds)
            existingIds.add(generatedId)
            autoGeneratedCache.set(cacheKey, generatedId)
            accountMap.set(entry.account, generatedId)

            // mf-accounts登録用に蓄積
            if (!newAccountsByClient.has(journal.client_id)) {
              newAccountsByClient.set(journal.client_id, [])
            }
            newAccountsByClient.get(journal.client_id)!.push({
              accountId: generatedId,
              name: entry.account,
              target: suffix === 'IND' ? 'individual' : 'corp',
              accountGroup: 'PL_EXPENSE',
              category: '',
              hidden: false,
              sortOrder: 9999,
            } as Account)

            autoGeneratedAccounts.push({
              clientId: journal.client_id,
              name: entry.account,
              accountId: generatedId,
            })
          }

          if (!dryRun) entry.account = generatedId
          accountAutoGenerated++
        }
      }

      // ── 税区分変換 ──
      if (entry.tax_category_id === null) {
        taxNull++
      } else if (isAlreadyNormalized(entry.tax_category_id)) {
        taxAlreadyNormalized++
      } else {
        const taxId = taxMap.get(entry.tax_category_id)
        if (taxId) {
          if (!dryRun) entry.tax_category_id = taxId
          taxConverted++
        } else {
          missedTaxes.add(entry.tax_category_id)
          taxMiss++
        }
      }
    }
  }

  // 5. 永続化（dryRunでなければ）
  if (!dryRun) {
    // confirmed_journals: replaceAll() が唯一の書き込み口（DL-050）
    replaceAll(journals as ConfirmedJournal[])

    // 自動発番した科目を client_mf_accounts に差分追加（saveMfAccounts経由）
    for (const [clientId, newAccounts] of newAccountsByClient) {
      if (hasClientAccounts(clientId)) {
        try {
          const clientData = getClientAccounts(clientId)
          const existing = [...clientData.accounts]
          const existingNameSet = new Set(existing.map(a => a.name))
          const toAdd = newAccounts.filter(a => !existingNameSet.has(a.name))
          if (toAdd.length > 0) {
            saveMfAccounts(clientId, [...existing, ...toAdd])
          }
        } catch {
          saveMfAccounts(clientId, newAccounts)
        }
      } else {
        saveMfAccounts(clientId, newAccounts)
      }
    }
  }

  return {
    journalCount: journals.length,
    accountConverted,
    accountAutoGenerated,
    accountAlreadyNormalized,
    taxConverted,
    taxAlreadyNormalized,
    taxNull,
    taxMiss,
    missedTaxNames: [...missedTaxes],
    autoGeneratedAccounts,
    dryRun,
  }
}
