/**
 * normalizeConfirmedJournalsService.ts — 確定済み仕訳の一括正規化サービス
 *
 * 【設計原則: DL-050】
 * データ変更は Application Service 経由のみ。
 * このサービスが唯一の正規化ロジック。APIもCLIも同じサービスを呼ぶ。
 *
 * 【責務】
 * - confirmed_journals の account/tax_category_id を MF名 → accountId/taxCategoryId に正規化
 * - マスタ外科目は generateMasterId() で自動発番し mf-accounts に自動登録
 * - 名前違い（消耗品→消耗品費等）は ALIAS_MAP で吸収
 *
 * 【データアクセス】
 * - 読み取り: confirmedJournalsApi.getAll()
 * - 書き込み: confirmedJournalsApi.replaceAll()
 * - 科目マスタ: accountMasterApi (getAllAccounts, getClientAccounts, saveMfAccounts)
 * - 税区分マスタ: accountMasterApi (getAllTaxCategories)
 *
 * ファイル直接操作（readFileSync/writeFileSync）は禁止。
 *
 * 準拠: DL-050, DL-042
 */

import { createMockRepositories } from '../../repositories/mock'
const repos = createMockRepositories()
const confirmedJournalRepo = repos.confirmedJournal
const clientRepo = repos.client
const accountMasterRepo = repos.accountMaster
const taxMasterRepo = repos.taxMaster
import { isIndividualType } from '../../constants/clientOptions'
import { generateMasterId } from './generateMasterId'
import type { Account } from '../../types/shared-account'
import { inferAccountGroupFromName } from '../../utils/inferAccountGroupFromName'

import { readFileSync } from 'fs'
import { resolve } from 'path'

/**
 * 名前違いの吸収マップ（MFマスタと異なる名称でCSVに入った科目）
 * #37修正: ハードコードからJSON外部化。data/account-alias-map.jsonから読み込み。
 */
function loadAliasMap(): Record<string, string> {
  try {
    const filePath = resolve(process.cwd(), 'data', 'account-alias-map.json')
    return JSON.parse(readFileSync(filePath, 'utf-8'))
  } catch (e) {
    console.warn('[normalizeConfirmedJournals] account-alias-map.json読み込み失敗。空マップで継続:', e)
    return {}
  }
}
const ALIAS_MAP: Record<string, string> = loadAliasMap()

// ────────────────────────────────────────────
// 型定義
// ────────────────────────────────────────────

export interface NormalizeResult {
  /** 処理対象の仕訳件数 */
  journalCount: number
  /** 科目: マスタヒット変換数 */
  accountConverted: number
  /** 科目: 自動発番数 */
  accountAutoGenerated: number
  /** 科目: 正規化済みスキップ数 */
  accountAlreadyNormalized: number
  /** 税区分: 変換成功数 */
  taxConverted: number
  /** 税区分: 正規化済みスキップ数 */
  taxAlreadyNormalized: number
  /** 税区分: null（スキップ）数 */
  taxNull: number
  /** 税区分: 免税事業者のnull→対象外に自動代入した数 */
  taxExemptFilled: number
  /** 税区分: 変換失敗（MISS）数 */
  taxMiss: number
  /** MISS税区分名一覧 */
  missedTaxNames: string[]
  /** 自動発番した科目（顧問先別） */
  autoGeneratedAccounts: Array<{ clientId: string; name: string; accountId: string }>
  /** ドライランかどうか */
  dryRun: boolean
}

// ────────────────────────────────────────────
// 内部ヘルパー
// ────────────────────────────────────────────

/** accountId形式（大文字英数+アンダースコア）かどうか */
function isAlreadyNormalized(value: string): boolean {
  return /^[A-Z][A-Z0-9_]+$/.test(value)
}

/** 顧問先のサフィックスを判定（CORP or IND） */
async function getSuffix(clientId: string): Promise<string> {
  try {
    const client = await clientRepo.getById(clientId)
    if (client && isIndividualType(client.type)) return 'IND'
  } catch { /* clientServiceが動かない場合はCORP */ }
  return 'CORP'
}

/**
 * 全社マスタ + 顧問先別MFデータから名前→accountIdの逆マップを構築
 * accountMasterApi 経由で取得（ファイル直接読みしない）
 */
async function buildAccountNameToIdMap(): Promise<{ map: Map<string, string>; existingIds: Set<string> }> {
  const map = new Map<string, string>()
  const existingIds = new Set<string>()

  // 全社マスタ — suffix付きキーも登録して CORP/IND を選び分け可能にする
  const allAccounts = await accountMasterRepo.getMaster()
  for (const a of allAccounts) {
    map.set(a.name, a.accountId)
    existingIds.add(a.accountId)
    const suffixMatch = a.accountId.match(/_(CORP|IND|FUDOUSAN_IND)$/)
    if (suffixMatch) {
      map.set(`${a.name}__${suffixMatch[1]}`, a.accountId)
    }
  }

  // 顧問先別MFデータ（clientsApi経由でclientId一覧を取得）
  const allClientsList = await clientRepo.getAll()
  const clientIds = new Set(allClientsList.map(c => c.clientId))

  for (const clientId of clientIds) {
    if (await accountMasterRepo.hasClientAccounts(clientId)) {
      try {
        const clientData = await accountMasterRepo.getClientAccountsFull(clientId)
        const accounts = clientData.accounts
        for (const a of accounts) {
          map.set(a.name, a.accountId)
          existingIds.add(a.accountId)
        }
      } catch { /* 未保存の場合はスキップ */ }
    }
  }

  return { map, existingIds }
}

/**
 * 税区分マスタから名前→taxCategoryIdの逆マップを構築
 * accountMasterApi 経由で取得
 */
async function buildTaxNameToIdMap(): Promise<Map<string, string>> {
  const map = new Map<string, string>()

  const allTaxes = await taxMasterRepo.getMaster()
  for (const t of allTaxes) {
    map.set(t.name, t.taxCategoryId)
  }

  return map
}

// ────────────────────────────────────────────
// メインサービス
// ────────────────────────────────────────────

/**
 * 確定済み仕訳の一括正規化を実行する
 *
 * - dryRun=true の場合、データ変更は行わず結果のみ返す
 * - dryRun=false の場合、replaceAll() でインメモリ+ファイルを一貫更新
 *
 * @param options.dryRun - ドライランモード（デフォルト: false）
 */
export async function normalizeConfirmedJournals(
  options: { dryRun?: boolean } = {},
): Promise<NormalizeResult> {
  const dryRun = options.dryRun ?? false

  // 1. マップ構築（accountMasterApi経由）
  const { map: accountMap, existingIds } = await buildAccountNameToIdMap()
  const taxMap = await buildTaxNameToIdMap()

  // 2. データ取得（clientIdループでRepository経由）
  const allClientsList = await clientRepo.getAll()
  const clientIds = [...new Set(allClientsList.map(c => c.clientId))]

  // 3. 変換統計

  let accountConverted = 0
  let accountAlreadyNormalized = 0
  let accountAutoGenerated = 0
  let taxConverted = 0
  let taxAlreadyNormalized = 0
  let taxMiss = 0
  let taxNull = 0
  let taxExemptFilled = 0
  const missedTaxes = new Set<string>()
  const autoGeneratedAccounts: NormalizeResult['autoGeneratedAccounts'] = []

  // 自動発番した科目の蓄積（顧問先別）
  const newAccountsByClient = new Map<string, Account[]>()
  // 発番済みキャッシュ（同じ科目名の2件目以降で再利用）
  const autoGeneratedCache = new Map<string, string>()

  // 免税デフォルト税区分ID（データ駆動: isExemptDefault=trueのtaxCategoryId）
  const allTaxes = await taxMasterRepo.getMaster()
  const exemptDefaultTaxId = allTaxes.find(t => t.isExemptDefault)?.taxCategoryId ?? null

  // 4. clientIdループで変換処理
  let totalJournalCount = 0
  for (const clientId of clientIds) {
    const journals = await confirmedJournalRepo.getByClientId(clientId)
    if (journals.length === 0) continue
    totalJournalCount += journals.length

    for (const journal of journals) {
      const entries = [...journal.debit_entries, ...journal.credit_entries]

      // 顧問先ごとの免税判定
      let isExempt = false
      try {
        const client = await clientRepo.getById(journal.client_id)
        isExempt = client?.consumptionTaxMode === 'exempt'
      } catch { /* clientService未起動時はfalse */ }

      for (const entry of entries) {
        // ── 科目変換 ──
        if (entry.account === null) {
          // 科目が未設定（null）の場合は科目変換をスキップ
        } else if (isAlreadyNormalized(entry.account)) {
          accountAlreadyNormalized++
        } else {
          // 名前違い吸収（消耗品→消耗品費 等）
          const aliasName = ALIAS_MAP[entry.account]
          const lookupName = aliasName ?? entry.account

          // suffix付きキーで優先検索（CORP/IND選び分け）
          const suffix = await getSuffix(journal.client_id)
          const id = accountMap.get(`${lookupName}__${suffix}`) ?? accountMap.get(lookupName)

          if (id) {
            if (!dryRun) entry.account = id
            accountConverted++
          } else {
            // マスタ外科目 → generateMasterIdで自動発番
            const cacheKey = `${journal.client_id}:${entry.account}`
            let generatedId = autoGeneratedCache.get(cacheKey)

            if (!generatedId) {
              generatedId = await generateMasterId(entry.account, suffix, existingIds)
              existingIds.add(generatedId)
              autoGeneratedCache.set(cacheKey, generatedId)
              accountMap.set(entry.account, generatedId)

              // mf-accounts登録用に蓄積
              if (!newAccountsByClient.has(journal.client_id)) {
                newAccountsByClient.set(journal.client_id, [])
              }
              newAccountsByClient.get(journal.client_id)!.push({
                accountId: generatedId,
                name: entry.account,
                target: suffix === 'IND' ? 'individual' : 'corp',
                accountGroup: inferAccountGroupFromName(entry.account),
                category: '',
                hidden: false,
                effectiveFrom: null,
                effectiveTo: null,
                sortOrder: 9999,
              })

              autoGeneratedAccounts.push({
                clientId: journal.client_id,
                name: entry.account,
                accountId: generatedId,
              })
            }

            if (!dryRun) entry.account = generatedId
            accountAutoGenerated++
          }
        }

        // ── 税区分変換 ──
        if (entry.tax_category_id === null) {
          if (isExempt && exemptDefaultTaxId) {
            // 免税事業者: MFがtax_nameを空で返すためnull → 「対象外」に正規化
            if (!dryRun) entry.tax_category_id = exemptDefaultTaxId
            taxExemptFilled++
          } else {
            taxNull++
          }
        } else if (isAlreadyNormalized(entry.tax_category_id)) {
          taxAlreadyNormalized++
        } else {
          const taxId = taxMap.get(entry.tax_category_id)
          if (taxId) {
            if (!dryRun) entry.tax_category_id = taxId
            taxConverted++
          } else {
            missedTaxes.add(entry.tax_category_id)
            taxMiss++
          }
        }
      }
    }

    // 5. 永続化（dryRunでなければ、clientId単位で保存）
    if (!dryRun) {
      // confirmed_journals: replaceByClient() でclientId単位で保存（DL-050）
      await confirmedJournalRepo.replaceByClientId(clientId, journals)
    }
  }

  // 自動発番した科目を client_mf_accounts に差分追加
  if (!dryRun) {
    for (const [clientId, newAccounts] of newAccountsByClient) {
      if (await accountMasterRepo.hasClientAccounts(clientId)) {
        try {
          const clientData = await accountMasterRepo.getClientAccountsFull(clientId)
          const existing = [...clientData.accounts]
          const existingNameSet = new Set(existing.map(a => a.name))
          const toAdd = newAccounts.filter(a => !existingNameSet.has(a.name))
          if (toAdd.length > 0) {
            await accountMasterRepo.saveMfAccounts(clientId, [...existing, ...toAdd])
          }
        } catch {
          await accountMasterRepo.saveMfAccounts(clientId, newAccounts)
        }
      } else {
        await accountMasterRepo.saveMfAccounts(clientId, newAccounts)
      }
    }
  }

  return {
    journalCount: totalJournalCount,
    accountConverted,
    accountAutoGenerated,
    accountAlreadyNormalized,
    taxConverted,
    taxAlreadyNormalized,
    taxNull,
    taxExemptFilled,
    taxMiss,
    missedTaxNames: [...missedTaxes],
    autoGeneratedAccounts,
    dryRun,
  }
}
